name: eslint-test
on: push

jobs:
  php-lint:
    name: Lint Test PHP files
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        echo "STATUS=true" >> $GITHUB_ENV

    - name: Setup PHP with fail-fast
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: oci8
        tools: composer

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install Open VPN
      run: sudo apt install openvpn -y && sudo apt install expect

    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '127.0.0.1'
        FILE_OVPN: '.github/vpn/config.ovpn'
        SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
      env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}

    - name: lint tests
      run: |
        cp .env.test .env &&
        ls -lha &&

        search_1="__DB_OPER_DB__" &&
        search_2="__DB_CFDI_HOST__" &&
        search_3="__DB_CFDI_DB__" &&
        search_4="__DB_CFDI_USER__" &&
        search_5="__DB_CFDI_PASS__" &&
        search_6="__DB_EGOB_DB__" &&
        search_7="__DB_TESORERIA_HOST__" &&
        search_8="__DB_TESORERIA_DB__" &&
        search_9="__DB_TESORERIA_USER__" &&
        search_10="__DB_TESORERIA_PASS__" &&
        search_11="__DB_PORTAL_HOST__" &&
        search_12="__DB_PORTAL_DB__" &&
        search_13="__DB_PORTAL_USER__" &&
        search_14="__DB_PORTAL_PASS__" &&
        search_15="__DB_ORACLE_HOST__" &&
        search_16="__DB_ORACLE_DB__" &&
        search_17="__DB_ORACLE_USER__" &&
        search_18="__DB_ORACLE_PASS__" &&
        search_19="__DB_ORACLE_SERVICE__" &&

        replace_1="${{ secrets.DB_OPER_DB }}" &&
        replace_2="${{ secrets.DB_CFDI_HOST }}" &&
        replace_3="${{ secrets.DB_CFDI_DB }}" &&
        replace_4="${{ secrets.DB_CFDI_USER }}" &&
        replace_5="${{ secrets.DB_CFDI_PASS }}" &&
        replace_6="${{ secrets.DB_EGOB_DB }}" &&
        replace_7="${{ secrets.DB_TESORERIA_HOST }}" &&
        replace_8="${{ secrets.DB_TESORERIA_DB }}" &&
        replace_9="${{ secrets.DB_TESORERIA_USER }}" &&
        replace_10="${{ secrets.DB_TESORERIA_PASS }}" &&
        replace_11="${{ secrets.DB_PORTAL_HOST }}" &&
        replace_12="${{ secrets.DB_PORTAL_DB }}" &&
        replace_13="${{ secrets.DB_PORTAL_USER }}" &&
        replace_14="${{ secrets.DB_PORTAL_PASS }}" &&
        replace_15="${{ secrets.DB_ORACLE_HOST }}" &&
        replace_16="${{ secrets.DB_ORACLE_DB }}" &&
        replace_17="${{ secrets.DB_ORACLE_USER }}" &&
        replace_18="${{ secrets.DB_ORACLE_PASS }}" &&
        replace_19="${{ secrets.DB_ORACLE_SERVICE }}" &&

        sed -i "s/$search_1/$replace_1/gi" .env &&
        sed -i "s/$search_2/$replace_2/gi" .env &&
        sed -i "s/$search_3/$replace_3/gi" .env &&
        sed -i "s/$search_4/$replace_4/gi" .env &&
        sed -i "s/$search_5/$replace_5/gi" .env &&
        sed -i "s/$search_6/$replace_6/gi" .env &&
        sed -i "s/$search_7/$replace_7/gi" .env &&
        sed -i "s/$search_8/$replace_8/gi" .env &&
        sed -i "s/$search_9/$replace_9/gi" .env &&
        sed -i "s/$search_10/$replace_10/gi" .env &&
        sed -i "s/$search_11/$replace_11/gi" .env &&
        sed -i "s/$search_12/$replace_12/gi" .env &&
        sed -i "s/$search_13/$replace_13/gi" .env &&
        sed -i "s/$search_14/$replace_14/gi" .env &&
        sed -i "s/$search_15/$replace_15/gi" .env &&
        sed -i "s/$search_16/$replace_16/gi" .env &&
        sed -i "s/$search_17/$replace_17/gi" .env &&
        sed -i "s/$search_18/$replace_18/gi" .env &&
        sed -i "s/$search_19/$replace_19/gi" .env &&
        
        composer install &&
        composer lint && echo "STATUS=false" >> $GITHUB_ENV

    - name: kill vpn
      if: always()
      run: sudo killall openvpn
